---
- hosts: localhost
  connection: local
  gather_facts: False
  sudo: False
  tasks:

    - name: check out roles needed for demo deployment from github.com
      git:
        repo: 'https://github.com/openstack-ansible/ansible-role-{{ item }}.git'
        dest: roles/{{ item }}
        update: yes
      with_items:
        - mysql
        - rabbitmq-server
        - keystone
        - nova-controller
        - neutron-controller

    - name: check out library needed for demo deployment from github.com
      git:
        repo: 
          'https://github.com/openstack-ansible/openstack-ansible-modules.git'
        dest: library/openstack-ansible-modules
        update: yes
