#!/bin/sh
ip addr del {{ neutron_external_network }} dev {{ neutron_network_netdev }}
ip link set {{ neutron_network_netdev }} up
ip link set {{ neutron_network_netdev }} promisc on
ip addr add {{ neutron_external_network }} dev br-ex
ip link set br-ex up
