#!/bin/bash
ipconfigs=$(ip addr show dev {{ openstack_network_external_device }} | perl -lne 'print "$1,$2" if /^\s*inet\s+((?:\d{1,3}\.){3}\d{1,3}\/\d+)\s+(?:brd\s+((?:\d{1,3}\.){3}\d{1,3}))?/')
gateway=$(ip route show | perl -lne 'print $1 if /^default\s.*via\s+((?:\d{1,3}\.){3}\d{1,3})/')
for ipconfig in $ipconfigs; do
    IFS=',' read ipaddr broadcast <<< "$ipconfig"
    ip addr del $ipaddr dev {{ openstack_network_external_device }}
    if [ -n "$broadcast" ]; then
        ip addr add $ipaddr broadcast $broadcast dev br-ex 
    else
        ip addr add $ipaddr dev br-ex 
    fi
done
ip link set {{ openstack_network_external_device }} up
ip link set {{ openstack_network_external_device }} promisc on
ip link set br-ex up
if [ -n "$gateway" ]; then
    ip route add default via $gateway 2>/dev/null
fi
ovs-vsctl --may-exist add-port br-ex {{ openstack_network_external_device }}

exit 0
