#!/bin/bash
netconfigs=$(ip addr show dev {{ openstack_network_external_device }} | perl -lne 'print "$1,$2" if /^\s*inet\s+((?:[0-9]{1,3}\.){3}[0-9]\/[0-9]+)\s+brd\s+((?:[0-9]{1,3}\.){3}[0-9])/')
for netconfig in $netconfigs; do
    IFS=',' read ipaddr broadcast <<< "$netconfig"
    ip addr del $ipaddr dev {{ openstack_network_external_device }}
done
ip link set {{ openstack_network_external_device }} up
ip link set {{ openstack_network_external_device }} promisc on
for netconfig in $netconfigs; do
    IFS=',' read ipaddr broadcast <<< "$netconfig"
    ip addr add $ipaddr broadcast $broadcast dev br-ex
done
ip addr add {{ openstack_network_external_ip }}/{{ openstack_network_external_netmask }} dev br-ex
ip link set br-ex up
